networks:
  itu-minitwit-network:
    external: false
    name: itu-minitwit-network

services:

  minitwit-database:
    container_name: minitwit-database
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
    ports:
      - 5432:5432
    networks:
      - itu-minitwit-network

  minitwit-service:
    container_name: minitwit-service
    depends_on:
      - minitwit-database
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
    build: .
    ports:
      - 8080:8080
    networks:
      - itu-minitwit-network

  minitwit-uitests:
    container_name: minitwit-uitests
    depends_on:
      - minitwit-service
    build: MiniTwitUITests
    networks:
      - itu-minitwit-network
