networks:
  itu-minitwit-network:
    external: false
    name: itu-minitwit-network

services:
  minitwit-database:
    container_name: minitwit-database
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
    ports:
      - 5432:5432
    networks:
      - itu-minitwit-network

  minitwit-service:
    container_name: minitwit-service
    depends_on:
      - minitwit-database
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
    build: .
    ports:
      - 8080:8080
    networks:
      - itu-minitwit-network

  minitwit-e2etests:
    image: cypress/included:12.3.0
    container_name: minitwit-e2etests
    volumes:
      - ./CypressGHA:/e2e
    working_dir: /e2e
    environment:
      - ELECTRON_DISABLE_GPU=true
    depends_on:
      - minitwit-service
    networks:
      - itu-minitwit-network
