networks:
  itu-minitwit-network:
    external: false
    name: itu-minitwit-network
  main:

services:
  minitwit-database:
    container_name: minitwit-database
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
    ports:
      - 5432:5432
    networks:
      - itu-minitwit-network
    depends_on:
      - fluentd
    volumes:
      - ./logs/minitwit_dotnet:/app/logs
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30
        tag: minitwit_database

  minitwit-service:
    container_name: minitwit-container
    depends_on:
      - minitwit-database
      - grafana
      - prometheus
      - fluentd
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
    build: .
    ports:
      - 8080:8080
    networks:
      - itu-minitwit-network
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30
        tag: minitwit_service

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./configuration_files/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - itu-minitwit-network
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30
        tag: prometheus

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    networks:
      - itu-minitwit-network
    volumes:
      - ./configuration_files/grafana_dashboard_setup.yaml:/etc/grafana/provisioning/dashboards/grafana_dashboard_setup.yaml
      - ./configuration_files/grafana_dashboard_0.json:/var/lib/grafana/dashboards/grafana_dashboard_0.json
      - ./configuration_files/grafana_dashboard_1.json:/var/lib/grafana/dashboards/grafana_dashboard_1.json
      - ./configuration_files/prometheus_datasource.yaml:/etc/grafana/provisioning/datasources/prometheus_datasource.yaml
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30
        tag: grafana

  fluentd:
    image: fluent/fluentd:v1.12-debian
    volumes:
      - ./configuration_files/fluent.conf:/fluentd/etc/fluent.conf
      #- ./fluentd/logs:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - itu-minitwit-network
