name: Pull Request Workflow

on:
  pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the application, test it, and create a Docker image
      run: docker-compose -f compose-test.yml up --force-recreate --abort-on-container-exit --exit-code-from minitwit-uitests
  
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  lint-dotnet:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Run NuGet restore
      run: dotnet restore <%path_to_project_or_solution%>
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis
      id: code-analysis
      with:
        build-breaking: true